formatting:
  # https://detekt.dev/docs/rules/formatting/#maximumlinelength
  # docks are saying to keep MaxLineLength or MaximumLineLength but it is not working this way.
  # ExampleAdapter.onCreateViewHolder is not working when we remove option below.
  # Exceeded max line length (120) [MaximumLineLength]
  MaximumLineLength:
    active: true
    maxLineLength: 130
  ArgumentListWrapping:
    active: true
    maxLineLength: 130
  TrailingCommaOnCallSite:
    active: true
  TrailingCommaOnDeclarationSite:
    active: true
  IfElseBracing:
    active: true
  ParameterListSpacing:
    active: true
  TryCatchFinallySpacing:
    active: true
  TypeArgumentListSpacing:
    active: true
  TypeParameterListSpacing:
    active: true
style:
  MaxLineLength:
    active: true
    maxLineLength: 130
    excludeRawStrings: true
  AlsoCouldBeApply:
    active: true
  MandatoryBracesIfStatements:
    active: true
    consistent: true
  CanBeNonNullable:
    active: true
  ClassOrdering:
    active: true
  CollapsibleIfStatements:
    active: true
  ExplicitCollectionElementAccessMethod:
    active: true
  ForbiddenAnnotation:
    active: true
  MandatoryBracesLoops:
    active: true
  NewLineAtEndOfFile:
    active: true
  OptionalUnit:
    active: true
  SpacingBetweenPackageAndImports:
    active: true
  TrailingWhitespace:
    active: true
  UnderscoresInNumericLiterals:
    active: true
  UnnecessaryBackticks:
    active: true
  UnnecessaryBracesAroundTrailingLambda:
    active: true
  UnnecessaryLet:
    active: true
  UnnecessaryParentheses:
    active: true
  UnusedImports:
    active: true
  UseEmptyCounterpart:
    active: true
  UseIfEmptyOrIfBlank:
    active: true
  UseSumOfInsteadOfFlatMapSize:
    active: true
coroutines:
  GlobalCoroutineUsage:
    active: true
  RedundantSuspendModifier:
    active: true
  SuspendFunWithCoroutineScopeReceiver:
    active: true
  SuspendFunWithFlowReturnType:
    active: true
exceptions:
  ObjectExtendsThrowable:
    active: true
performance:
  CouldBeSequence:
    active: true
potential-bugs:
  CastToNullableType:
    active: true
  ElseCaseInsteadOfExhaustiveWhen:
    active: true
  MissingPackageDeclaration:
    active: true
  NullCheckOnMutableProperty:
    active: true
  PropertyUsedBeforeDeclaration:
    active: true
  UnnecessaryNotNullCheck:
    active: true
