coroutines:
  GlobalCoroutineUsage:
    active: true
  RedundantSuspendModifier:
    active: true
  SuspendFunWithCoroutineScopeReceiver:
    active: true
  SuspendFunWithFlowReturnType:
    active: true
exceptions:
  ObjectExtendsThrowable:
    active: true
formatting:
  # https://detekt.dev/docs/rules/formatting/#maximumlinelength
  # docks are saying to keep MaxLineLength or MaximumLineLength but it is not working this way.
  # ExampleAdapter.onCreateViewHolder is not working when we remove option below.
  # Exceeded max line length (120) [MaximumLineLength]
  # https://github.com/detekt/detekt/issues/7551
  MaximumLineLength:
    active: true
    maxLineLength: 130
  ArgumentListWrapping:
    active: true
    maxLineLength: 130
  EnumEntryNameCase:
    active: true
  EnumWrapping:
    active: true
  IfElseBracing:
    active: true
  ParameterListSpacing:
    active: true
  PropertyName:
    active: true
  TrailingCommaOnCallSite:
    active: true
  TrailingCommaOnDeclarationSite:
    active: true
  TryCatchFinallySpacing:
    active: true
  TypeArgumentListSpacing:
    active: true
  TypeParameterListSpacing:
    active: true
naming:
  BooleanPropertyNaming:
    active: true
    allowedPattern: '^(is|has|are|should|can)'
  ForbiddenClassName:
    active: true
    forbiddenName:
      - Helper
  NonBooleanPropertyPrefixedWithIs:
    active: true
performance:
  CouldBeSequence:
    active: true
potential-bugs:
  CastToNullableType:
    active: true
  DontDowncastCollectionTypes:
    active: true
  ElseCaseInsteadOfExhaustiveWhen:
    active: true
  MissingPackageDeclaration:
    active: true
  NullableToStringCall:
    active: true
  NullCheckOnMutableProperty:
    active: true
  PropertyUsedBeforeDeclaration:
    active: true
  UnconditionalJumpStatementInLoop:
    active: true
  UnnecessaryNotNullCheck:
    active: true
style:
  MaxLineLength:
    active: true
    maxLineLength: 130
    excludeRawStrings: true
  AlsoCouldBeApply:
    active: true
  BracesOnIfStatements:
    active: true
    singleLine: 'consistent'
    multiLine: 'always'
  BracesOnWhenStatements:
    active: true
    singleLine: 'necessary'
    multiLine: 'necessary'
  CanBeNonNullable:
    active: true
  ClassOrdering:
    active: true
  CollapsibleIfStatements:
    active: true
  DoubleNegativeLambda:
    active: true
  EqualsOnSignatureLine:
    active: true
  ExplicitCollectionElementAccessMethod:
    active: true
  ExpressionBodySyntax:
    active: true
  ForbiddenAnnotation:
    active: true
  MandatoryBracesLoops:
    active: true
  NewLineAtEndOfFile:
    active: true
  NoTabs:
    active: true
  NullableBooleanCheck:
    active: true
  OptionalUnit:
    active: true
  RedundantVisibilityModifierRule:
    active: true
  SpacingBetweenPackageAndImports:
    active: true
  TrailingWhitespace:
    active: true
  UnderscoresInNumericLiterals:
    active: true
  UnnecessaryAnnotationUseSiteTarget:
    active: true
  UnnecessaryBackticks:
    active: true
  UnnecessaryBracesAroundTrailingLambda:
    active: true
  UnnecessaryLet:
    active: true
  UnnecessaryParentheses:
    active: true
  UnusedImports:
    active: true
  UseEmptyCounterpart:
    active: true
  UseIfEmptyOrIfBlank:
    active: true
  UseIfInsteadOfWhen:
    active: true
  UseSumOfInsteadOfFlatMapSize:
    active: true
