name: Android CI

on:
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up environment for Android build
        uses: ./.github/actions/prepare-env
      - name: Lint
        run: ./gradlew lintDebug
      - name: Build with Gradle
        run: ./gradlew buildDebug
  instrumentation-tests:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up environment for Android build
        uses: ./.github/actions/prepare-env
      - name: Instrumentation tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 33
          target: default
          arch: x86_64
          script: ./gradlew connectedCheck --stacktrace
  analyze:
    name: CodeQL
    timeout-minutes: 360
    permissions:
      actions: read
      contents: read
      security-events: write

    strategy:
      fail-fast: false
      matrix:
        language: [ 'java-kotlin' ]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: ${{ matrix.language }}
      - name: Set up environment for Android build
        uses: ./.github/actions/prepare-env
      - name: Build with Gradle
        run: ./gradlew buildDebug
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2
        with:
          category: "/language:${{matrix.language}}"
